### ISSUE TITLE
关于 Karabiner  的删除

### ISSUE THREAD

**Issue by gy134340** [Louiszhai/tool#8]
这个装完似乎没有办法很好的删除，可以试一下，从应用程序中删除总是被锁定住

在活动监视器中强制杀死进程都杀不掉

![image](https://user-images.githubusercontent.com/14243932/56851579-4aca2d80-6943-11e9-9fa4-c11463b3d430.png)

对于 
![image](https://user-images.githubusercontent.com/14243932/56851558-0b034600-6943-11e9-9f91-a0bf0e53a282.png)

**Comment by gy134340** [comment]
这个 app 这里做的有点 trick 了，删除居然在这里，别的地方怎么删都删不动

![image](https://user-images.githubusercontent.com/14243932/56851690-697cf400-6944-11e9-820b-9aa80b602da1.png)

**Comment by sevenzh** [comment]
打开terminal，切换到root用户，cd /Applications 进入应用程序目录；chflags -R noschg Karabiner*；chflags -R nouchg Karabiner； rm -fr Karabiner*；

**Comment by apollo007fd** [comment]
> Applications

这样确实可以删，但是
设置 -> 键盘 -> 修饰键 -> 选择键盘, 还是有Karabiner
大佬帮忙看看怎么去掉这里的Karabiner选项

**Comment by apollo007fd** [comment]
> 打开terminal，切换到root用户，cd /Applications 进入应用程序目录；chflags -R noschg Karabiner*；chflags -R nouchg Karabiner； rm -fr Karabiner*；

找到了，sudo /Library/Application\ Support/org.pqrs/Karabiner-Elements/uninstall.sh， 这样即可完全删掉
